# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_interpolator', [dirname(__file__)])
        except ImportError:
            import _interpolator
            return _interpolator
        if fp is not None:
            try:
                _mod = imp.load_module('_interpolator', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _interpolator = swig_import_helper()
    del swig_import_helper
else:
    import _interpolator
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class Interpolator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Interpolator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Interpolator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _interpolator.delete_Interpolator
    __del__ = lambda self : None;
    def Interp(self, *args): return _interpolator.Interpolator_Interp(self, *args)
Interpolator_swigregister = _interpolator.Interpolator_swigregister
Interpolator_swigregister(Interpolator)

class LinInterp(Interpolator):
    __swig_setmethods__ = {}
    for _s in [Interpolator]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, LinInterp, name, value)
    __swig_getmethods__ = {}
    for _s in [Interpolator]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, LinInterp, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _interpolator.new_LinInterp()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _interpolator.delete_LinInterp
    __del__ = lambda self : None;
    def Interp(self, *args): return _interpolator.LinInterp_Interp(self, *args)
LinInterp_swigregister = _interpolator.LinInterp_swigregister
LinInterp_swigregister(LinInterp)

class CubicInterp(Interpolator):
    __swig_setmethods__ = {}
    for _s in [Interpolator]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, CubicInterp, name, value)
    __swig_getmethods__ = {}
    for _s in [Interpolator]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, CubicInterp, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _interpolator.new_CubicInterp()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _interpolator.delete_CubicInterp
    __del__ = lambda self : None;
    def Interp(self, *args): return _interpolator.CubicInterp_Interp(self, *args)
CubicInterp_swigregister = _interpolator.CubicInterp_swigregister
CubicInterp_swigregister(CubicInterp)

class HermiteInterp(Interpolator):
    __swig_setmethods__ = {}
    for _s in [Interpolator]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, HermiteInterp, name, value)
    __swig_getmethods__ = {}
    for _s in [Interpolator]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, HermiteInterp, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _interpolator.new_HermiteInterp()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _interpolator.delete_HermiteInterp
    __del__ = lambda self : None;
    def Interp(self, *args): return _interpolator.HermiteInterp_Interp(self, *args)
HermiteInterp_swigregister = _interpolator.HermiteInterp_swigregister
HermiteInterp_swigregister(HermiteInterp)

# This file is compatible with both classic and new-style classes.


